#!/bin/bash
# universal spark configuration file

SPARK_HOME=/software/spark/2.3.0
SPARK_MASTER_HOST=`hostname -s`
SPARK_MASTER_PORT=7077
SPARK_MASTER_WEBUI_PORT=8080
SPARK_LOG_DIR=$SLURM_SUBMIT_DIR/spark_logs
SPARK_WORKER_DIR=${SPARK_WORKER_DIR:-$SLURM_SUBMIT_DIR}
SPARK_WORKER_CORES=$SLURM_NTASKS_PER_NODE
SPARK_WORKER_MEMORY="${SLURM_MEM_PER_NODE}M"

